Pemanggilan'path'
```
liat'data
```

In [1]:
import pandas as pd
import numpy as np

# pengaturan tampilan biar bersih
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)

path=r'C:\Users\sayyi\Downloads\sales.csv'

null_value = ['None', 'none', 'null', '?', ' ', '   ', 'n/a', 'na', '--', '-']

csv = pd.read_csv(path, na_values=null_value)

# output
print("Jumlah Data: ",csv.shape)
print("\nKolom & tipe data: \n", csv.dtypes)
print("\n5 baris pertama:")
csv.head()

Jumlah Data:  (89984, 23)

Kolom & tipe data:
 Order_ID                 str
Order_Date               str
Customer_ID              str
Customer_Age         float64
Gender                   str
City                     str
Region                   str
Customer_Segment         str
Sales_Channel            str
Product_ID               str
Product_Category         str
Product_Name             str
Unit_Price           float64
Quantity             float64
Discount_Percent     float64
Shipping_Cost        float64
Payment_Method           str
Order_Status             str
Return_Flag              str
Marketing_Channel        str
Customer_Rating      float64
Sales_Amount         float64
Profit_Margin        float64
dtype: object

5 baris pertama:

      Order_ID  Order_Date Customer_ID  Customer_Age  Gender        City  Region Customer_Segment Sales_Channel Product_ID Product_Category  Product_Name  Unit_Price  Quantity  Discount_Percent  Shipping_Cost    Payment_Method Order_Status Return_Flag Marketing_Channel  Customer_Rating  Sales_Amount  Profit_Margin
0  ORD-0000001  2024-01-09  CUS-020443          64.0  Female     Karachi   Sindh        Corporate  Retail Store    PRD-018  Office Supplies  Laptop Stand     3746.16       2.0              8.33         119.36       Credit Card    Delivered          No            Direct              5.0       6987.71          27.20
1  ORD-0000002  2025-06-13  CUS-025451          40.0    Male  Rawalpindi  Punjab              New   Marketplace    PRD-011   Home & Kitchen  Bedsheet Set     4203.05       1.0              9.38         167.96  Cash on Delivery    Delivered          No      Social Media              5.0       3976.91          31.46
2  ORD-0000003  2025-09-25  CUS-022569          56.0    Male      Lahore  Punjab        Returning   Marketplace    PRD-021     Toys & Games    Board Game     2723.85       5.0             17.63         250.01        Debit Card    Delivered          No            Search              3.0      11467.71          30.81
3  ORD-0000004  2024-01-01  CUS-010322          31.0    male  Rawalpindi  Punjab            Loyal   Marketplace    PRD-017  Office Supplies  Office Chair    24977.53       3.0              8.10            NaN  Cash on Delivery    Delivered          No            Direct              5.0      69182.12          25.20
4  ORD-0000005  2024-01-29  CUS-008308          42.0  Female  Gujranwala  Punjab            Loyal   Marketplace    PRD-012   Home & Kitchen     Desk Lamp     2995.38       4.0             15.37         348.78  Cash on Delivery    Delivered          No      Social Media              NaN      10489.07          26.54

---
deteksi Nan value menggunakan metode eksplisit

In [2]:
count_null=csv.isna().sum()
percent_null=(csv.isna().mean()*100).round(2)

summary=pd.DataFrame({ 
    'Missing':count_null,
    'Percentage':percent_null
}).sort_values('Missing',ascending=False)

display(summary[summary['Missing']>0])

                   Missing  Percentage
Customer_Rating      22558       25.07
Marketing_Channel     7619        8.47
Shipping_Cost         6779        7.53
Payment_Method        5959        6.62
Customer_Age          4966        5.52
Customer_Segment      4121        4.58
Discount_Percent      4058        4.51
Profit_Margin         3224        3.58
Gender                3161        3.51
Unit_Price            2516        2.80
City                  2205        2.45
Order_Status          2020        2.24
Sales_Channel         1675        1.86
Product_Name          1672        1.86
Product_Category      1079        1.20
Quantity               998        1.11

In [3]:
csv.head(0)
# print(csv["Gender"].to_string(index=False))

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Age, Gender, City, Region, Customer_Segment, Sales_Channel, Product_ID, Product_Category, Product_Name, Unit_Price, Quantity, Discount_Percent, Shipping_Cost, Payment_Method, Order_Status, Return_Flag, Marketing_Channel, Customer_Rating, Sales_Amount, Profit_Margin]
Index: []

In [4]:
print("-"*10)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.width',100)

print(f"Umur pembeli tidak masuk akal ")
print(f"Umur customer Dibawah 5 tahun : {(csv['Customer_Age'] < 5).sum()}")
print(f"Umur customer Diatas 80 tahun : {(csv['Customer_Age'] > 80).sum()}")

print(f"\nHarga minus : {(csv["Unit_Price"] < 0).sum()}")
print(f"DIscount negatif : {(csv["Discount_Percent"] < 0).sum()}")
print(f"profit minus: {(csv["Profit_Margin"] < 0).sum()}")
print(f"diskon 100%: {(csv["Discount_Percent"] > 100).sum()}")

print(f"\n\nGender tidak konsisten: ")
# print(f"{csv['Gender'].unique()}")
pd.Series(csv['Gender'].unique()).sort_values()

----------
Umur pembeli tidak masuk akal
Umur customer Dibawah 5 tahun : 9
Umur customer Diatas 80 tahun : 18

Harga minus : 17
DIscount negatif : 7
profit minus: 285
diskon 100%: 8


Gender tidak konsisten:

10              FEMALE
9                 MALE
6                     F
0                Female
8                     M
1                  Male
5            Non-binary
4     Prefer not to say
7                female
2                  male
3                   NaN
dtype: str

---
# STEP 2: Menampilkan data yang bemaslaah

In [5]:
print("Data dengan harga minus")
display(csv.loc[csv["Unit_Price"] < 0, ["Order_ID", "Product_Name", "Unit_Price", "Quantity", "Sales_Amount"]])

print("\nData dengan discount minus")
display(csv.loc[csv["Discount_Percent"] < 0, ["Order_ID", "Product_Name", "Discount_Percent", "Quantity", "Sales_Amount"]])

print("\nData dengan profit minus")
display(csv.loc[csv["Profit_Margin"] < 0, ["Order_ID", "Product_Name", "Profit_Margin", "Quantity", "Sales_Amount"]])

print("\nData dengan diskon 100%")
display(csv.loc[csv["Discount_Percent"] > 100, ["Order_ID", "Product_Name", "Discount_Percent", "Quantity", "Sales_Amount"]])

print("\nData dengan gender tidak konsisten")
display(csv.loc[csv["Gender"] == "Non-binary", ["Order_ID", "Product_Name", "Gender", "Quantity", "Sales_Amount"]])

Data dengan harga minus

          Order_ID         Product_Name  Unit_Price  Quantity  Sales_Amount
806    ORD-0000807  Wireless Headphones      -250.0       1.0       7479.24
7561   ORD-0007562          Denim Jeans        -1.0       1.0       3447.81
15907  ORD-0015908           Face Serum      -250.0       1.0       2500.42
19072  ORD-0019073                  NaN        -1.0       3.0      10085.33
19553  ORD-0019554    Smart Watch Strap      -250.0       3.0       4004.38
36474  ORD-0036475  Wireless Headphones      -250.0       2.0      18181.68
42384  ORD-0042385      Travel Backpack        -1.0       2.0       6929.71
42432  ORD-0042433       Cotton T-Shirt      -250.0       2.0       2720.55
43211  ORD-0043212            Air Fryer      -250.0       3.0      45899.76
49273  ORD-0049274           Face Serum        -1.0       2.0       4206.39
52244  ORD-0052245            USB-C Hub        -1.0       3.0      12354.84
67285  ORD-0067286            Air Fryer        -1.0       2.0      35512.19
67662  ORD-0067663           Face Serum        -1.0       1.0       2692.78
71320  ORD-0071321       Cotton T-Shirt      -250.0       3.0       4014.21
74178  ORD-0074179    Bluetooth Speaker        -1.0       1.0       5825.35
80222  ORD-0080223        Notebook Pack        -1.0       3.0       2045.55
88508  ORD-0088509          Denim Jeans      -250.0       2.0       6805.38

Data dengan discount minus

          Order_ID       Product_Name  Discount_Percent  Quantity  Sales_Amount
34052  ORD-0034053       Bedsheet Set              -5.0       3.0      13412.44
36291  ORD-0036292  Smart Watch Strap              -5.0       4.0       5320.79
40582  ORD-0040583         Face Serum              -5.0       4.0       8028.21
41294  ORD-0041295    Travel Backpack              -5.0       7.0      26535.55
46464  ORD-0046465  Bluetooth Speaker              -5.0       4.0      23080.60
60988  ORD-0060989      Skin Care Kit              -5.0       4.0      19623.31
78092  ORD-0078093        Denim Jeans              -5.0       2.0       7228.75

Data dengan profit minus

          Order_ID         Product_Name  Profit_Margin  Quantity  Sales_Amount
39     ORD-0000040           Power Bank          -6.56       3.0      11267.29
73     ORD-0000074            USB-C Hub          -1.31       3.0       9168.00
458    ORD-0000459           Power Bank          -0.33       2.0       7519.82
923    ORD-0000924           Power Bank          -0.35       3.0       8856.52
924    ORD-0000925            USB-C Hub          -0.40       3.0      11487.26
1007   ORD-0001008         Office Chair         -11.88       NaN      13333.71
1138   ORD-0001139  Wireless Headphones          -1.80       5.0      31501.82
1628   ORD-0001629           Power Bank          -6.32       2.0       6591.66
2226   ORD-0002227            USB-C Hub          -2.15       2.0       7020.15
2238   ORD-0002239            USB-C Hub          -2.09       2.0       7756.39
2990   ORD-0002991           Power Bank          -5.45       1.0       3218.98
3031   ORD-0003032           Power Bank          -2.46       3.0       9292.85
3121   ORD-0003122           Power Bank         -13.80       4.0      12476.22
3301   ORD-0003302  Wireless Headphones          -2.30       2.0      13980.68
3410   ORD-0003411           Power Bank          -3.53       4.0      13526.33
3623   ORD-0003624  Wireless Headphones          -0.17       2.0      11527.29
3682   ORD-0003683  Wireless Headphones          -2.80       3.0      20114.22
4546   ORD-0004547           Power Bank          -0.26       2.0       5598.92
4880   ORD-0004881         Office Chair          -5.44       2.0      34030.60
5394   ORD-0005395  Wireless Headphones          -4.70       1.0       6659.78
5577   ORD-0005578    Bluetooth Speaker          -7.70       1.0       5250.55
5759   ORD-0005760  Wireless Headphones          -2.72       NaN      39080.97
6362   ORD-0006363           Power Bank          -0.21       2.0       7604.00
6872   ORD-0006873           Power Bank         -10.60       1.0       3277.19
7061   ORD-0007062         Office Chair          -5.17       1.0      17297.25
7250   ORD-0007251            USB-C Hub          -6.99       3.0       9723.45
7477   ORD-0007478            USB-C Hub          -1.56       1.0       3447.32
7548   ORD-0007549            USB-C Hub          -2.17       2.0       7773.89
7750   ORD-0007751  Wireless Headphones          -2.15       2.0      13815.43
8685   ORD-0008686            USB-C Hub          -0.27       1.0       3736.60
8703   ORD-0008704  Wireless Headphones          -3.53       4.0      27486.99
9494   ORD-0009495    Bluetooth Speaker          -1.26       3.0      17846.44
9497   ORD-0009498            USB-C Hub          -9.17       1.0       4219.16
10020  ORD-0010021    Bluetooth Speaker          -6.11       2.0       8793.60
10150  ORD-0010151         Office Chair          -2.67       5.0      87043.94
10431  ORD-0010432         Office Chair          -1.01       3.0      46468.28
10437  ORD-0010438           Power Bank          -1.65       2.0       6095.89
11074  ORD-0011075  Wireless Headphones          -3.08       2.0      12634.49
11135  ORD-0011136            USB-C Hub          -1.54       3.0      13783.26
11310  ORD-0011311            USB-C Hub          -3.69       2.0       7952.64
11317  ORD-0011318    Bluetooth Speaker          -3.19       1.0       4746.92
11357  ORD-0011358  Wireless Headphones          -0.55       3.0      20822.10
13163  ORD-0013164  Wireless Headphones          -0.33       3.0      22688.64
13247  ORD-0013248           Power Bank          -0.94       1.0       3025.48
14035  ORD-0014036            USB-C Hub          -0.07       5.0      23626.50
14057  ORD-0014058         Office Chair          -2.64       2.0      30653.31
14325  ORD-0014326    Bluetooth Speaker          -0.51       2.0       9337.22
14997  ORD-0014998    Bluetooth Speaker          -0.23       2.0      11028.91
15012  ORD-0015013           Power Bank          -2.01       3.0       8564.73
15525  ORD-0015526       Cotton T-Shirt          -0.69       3.0       3421.38
15530  ORD-0015531            USB-C Hub          -1.00       2.0       6491.70
15944  ORD-0015945           Power Bank          -3.18       1.0       3051.42
16499  ORD-0016500           Power Bank          -2.24       2.0       6681.97
16897  ORD-0016898    Bluetooth Speaker          -1.30       4.0      18755.83
17316  ORD-0017317  Wireless Headphones          -0.97       2.0      16190.83
17338  ORD-0017339           Power Bank          -3.51       2.0       7000.72
17588  ORD-0017589    Bluetooth Speaker          -0.85       1.0       6365.10
18058  ORD-0018059            USB-C Hub          -5.17       1.0       3646.23
18814  ORD-0018815    Bluetooth Speaker          -0.44       5.0      25621.17
18825  ORD-0018826            USB-C Hub          -3.01       1.0       4583.85
19671  ORD-0019672            Air Fryer          -2.44       1.0      10517.79
20121  ORD-0020122           Power Bank          -1.21       1.0       4027.14
20289  ORD-0020290            USB-C Hub          -3.70       1.0       4522.72
20396  ORD-0020397            USB-C Hub          -2.34       4.0      13441.44
20446  ORD-0020447  Wireless Headphones          -3.63       3.0      20820.76
20787  ORD-0020788         Office Chair          -0.76       1.0      17689.30
21253  ORD-0021254  Wireless Headphones          -3.23       1.0       8214.39
21358  ORD-0021359            USB-C Hub          -4.01       2.0       8112.92
21464  ORD-0021465           Power Bank          -1.18       1.0       3153.71
21739  ORD-0021740        Running Shoes          -0.03       2.0      10691.90
22201  ORD-0022202  Wireless Headphones          -5.43       2.0      14773.65
22392  ORD-0022393            Air Fryer          -1.05       2.0      26193.31
22558  ORD-0022559    Bluetooth Speaker          -1.13       1.0       4721.47
23872  ORD-0023873    Bluetooth Speaker          -0.01       3.0      17190.95
24319  ORD-0024320           Power Bank          -0.10       1.0       3862.14
24361  ORD-0024362        Winter Jacket          -0.23       1.0       6945.03
24496  ORD-0024497            USB-C Hub          -2.02       1.0       4225.40
24806  ORD-0024807           Power Bank          -1.48       3.0       9998.93
25392  ORD-0025393            USB-C Hub          -1.09       1.0       4432.14
25610  ORD-0025611  Wireless Headphones          -6.83       1.0       6850.00
26456  ORD-0026457  Wireless Headphones          -6.97       2.0      11473.75
26554  ORD-0026555  Wireless Headphones          -0.31       1.0       7322.12
26610  ORD-0026611      Travel Backpack          -1.30       2.0       6268.21
26786  ORD-0026787           Power Bank          -1.72       3.0      11742.00
27004  ORD-0027005           Power Bank          -1.16       3.0       8063.06
27496  ORD-0027497    Bluetooth Speaker          -2.26       2.0      10987.78
27499  ORD-0027500                  NaN          -5.37       2.0       6320.19
27562  ORD-0027563  Wireless Headphones          -1.72       2.0      13944.93
27886  ORD-0027887           Power Bank          -4.53       3.0       9438.20
27975  ORD-0027976           Power Bank          -4.82       2.0       6708.50
29047  ORD-0029048  Wireless Headphones          -3.10       2.0      11135.03
29753  ORD-0029754            Air Fryer          -1.26       1.0      19045.99
29892  ORD-0029893  Wireless Headphones          -9.53       2.0      16776.83
29895  ORD-0029896            USB-C Hub          -1.37       1.0       4550.37
30222  ORD-0030223            USB-C Hub          -0.58       5.0      16974.55
30304  ORD-0030305  Wireless Headphones          -1.69       4.0      27290.08
30673  ORD-0030674           Power Bank          -1.44       3.0       9618.00
31155  ORD-0031156    Bluetooth Speaker          -1.52       3.0      17707.17
31580  ORD-0071382            Air Fryer         -12.07       1.0      10135.00
31709  ORD-0031710            USB-C Hub          -1.32       1.0       3884.19
31767  ORD-0031768    Bluetooth Speaker          -0.24       2.0       9701.09
31792  ORD-0031793           Power Bank          -5.75       2.0       6487.88
33215  ORD-0033216    Bluetooth Speaker          -0.10       2.0      12177.53
33794  ORD-0033795    Bluetooth Speaker          -6.18       1.0       5495.03
35098  ORD-0035099  Wireless Headphones          -1.77       2.0      13624.34
35251  ORD-0035252  Wireless Headphones          -2.44       2.0      13401.53
35285  ORD-0035286    Bluetooth Speaker          -3.25       2.0      12634.99
35322  ORD-0035323    Bluetooth Speaker          -5.05       1.0       5357.90
35362  ORD-0035363            Air Fryer          -1.06       2.0      26800.46
35558  ORD-0035559    Bluetooth Speaker          -2.16       2.0       8073.71
35738  ORD-0035739            USB-C Hub          -0.28       3.0       9076.22
35783  ORD-0035784    Bluetooth Speaker          -2.45       2.0      11140.74
36331  ORD-0036332            USB-C Hub          -5.00       1.0       3573.80
36341  ORD-0036342           Power Bank          -0.97       1.0       3372.95
37079  ORD-0037080            USB-C Hub          -0.48       2.0       6938.12
38768  ORD-0038769  Wireless Headphones          -2.94       3.0      20772.56
38770  ORD-0038771    Bluetooth Speaker          -2.50       2.0      10320.17
38931  ORD-0038932            Air Fryer          -2.97       4.0      58629.55
39235  ORD-0039236           Power Bank          -1.42       1.0       3042.56
39912  ORD-0039913           Power Bank          -3.88       2.0       5860.62
40065  ORD-0040066        Running Shoes          -4.61       3.0      13168.97
40837  ORD-0040838  Wireless Headphones          -1.12       1.0       7665.81
41075  ORD-0041076            USB-C Hub          -0.72       2.0       7624.29
41395  ORD-0041396            USB-C Hub          -1.15       2.0       7221.82
41658  ORD-0041659  Wireless Headphones          -2.99       3.0      24407.16
42085  ORD-0042086                  NaN          -1.78       1.0       3222.94
42486  ORD-0042487  Wireless Headphones          -7.87       2.0      13577.04
42589  ORD-0042590            USB-C Hub          -4.54       2.0       6262.48
42669  ORD-0042670         Office Chair          -1.20       1.0      17968.35
43006  ORD-0043007           Power Bank          -0.67       2.0       6863.67
43936  ORD-0043937    Bluetooth Speaker          -1.73       1.0       5921.38
44411  ORD-0044412  Wireless Headphones          -0.98       1.0       7475.38
44642  ORD-0044643            Desk Lamp          -1.87       4.0       8860.33
44763  ORD-0044764           Power Bank          -7.07       1.0       3403.98
44960  ORD-0044961            USB-C Hub          -4.35       3.0       8014.88
45007  ORD-0045008            USB-C Hub          -5.46       1.0       4498.04
45806  ORD-0045807           Power Bank          -3.67       1.0       3400.33
45970  ORD-0045971            USB-C Hub         -10.54       3.0      11573.85
46476  ORD-0046477           Power Bank         -10.53       4.0      13329.76
47070  ORD-0047071           Power Bank          -6.47       4.0      13625.08
47171  ORD-0047172            USB-C Hub          -3.20       2.0       7847.56
47696  ORD-0047697           Power Bank          -4.25       2.0       5890.12
47703  ORD-0047704    Bluetooth Speaker          -1.47       2.0      10355.51
48271  ORD-0048272    Bluetooth Speaker          -1.95       2.0      11193.45
48370  ORD-0048371           Power Bank          -3.48       1.0       3380.07
48570  ORD-0048571    Bluetooth Speaker          -0.30       1.0       5826.37
48758  ORD-0048759  Wireless Headphones          -0.52       1.0       8012.63
49482  ORD-0049483           Power Bank          -1.03       2.0       6241.45
49530  ORD-0049531                  NaN          -4.08       1.0       3323.08
50199  ORD-0050200           Power Bank          -2.70       3.0      11014.93
50349  ORD-0050350           Power Bank          -4.14       1.0       3830.78
50402  ORD-0050403           Power Bank          -6.70       2.0       6167.11
50815  ORD-0050816            USB-C Hub          -0.81       3.0      10695.67
51429  ORD-0051430            USB-C Hub          -8.65       2.0       6768.97
51459  ORD-0051460            USB-C Hub          -6.64       2.0       7978.68
51707  ORD-0051708            Air Fryer          -1.96       7.0     105816.62
52378  ORD-0052379  Wireless Headphones          -2.89       1.0       7756.41
52934  ORD-0052935           Power Bank          -0.27       2.0       7212.12
53699  ORD-0053700        Winter Jacket          -2.82       1.0       6916.07
53875  ORD-0053876            Air Fryer          -0.50       2.0      25607.54
53922  ORD-0053923           Power Bank          -2.01       2.0       7211.63
54370  ORD-0054371          Denim Jeans          -0.51       4.0      11581.81
55077  ORD-0055078           Power Bank          -6.37       1.0       3373.63
55121  ORD-0055122            Air Fryer          -0.82       2.0      33084.27
55159  ORD-0055160           Power Bank          -3.43       1.0       2730.08
55357  ORD-0055358           Power Bank          -5.52       2.0       4963.09
55463  ORD-0055464           Power Bank          -1.47       3.0       8581.28
55558  ORD-0055559                  NaN          -0.59       2.0       6250.40
55592  ORD-0055593            USB-C Hub          -0.92       3.0      12123.26
55719  ORD-0055720        Running Shoes          -1.92       3.0      16162.89
56196  ORD-0056197            USB-C Hub          -2.19       2.0       9175.04
56235  ORD-0056236            USB-C Hub          -3.95       2.0       8076.92
56876  ORD-0056877            USB-C Hub          -5.89       2.0       7591.14
57010  ORD-0057011           Power Bank          -2.51       6.0      16597.49
57860  ORD-0057861           Power Bank          -0.62       3.0      11085.07
58459  ORD-0058460           Power Bank          -0.40       3.0      10756.76
58972  ORD-0058973            Air Fryer          -0.08       2.0      25492.32
59003  ORD-0059004           Power Bank          -1.42       1.0       3037.93
59657  ORD-0059658  Wireless Headphones          -0.46       2.0      11313.42
59849  ORD-0059850    Bluetooth Speaker          -1.60       1.0       4483.75
60382  ORD-0060383           Power Bank          -9.60       1.0       3123.54
60728  ORD-0060729           Power Bank          -3.15       3.0      10218.16
60736  ORD-0060737  Wireless Headphones          -0.25       3.0      19624.59
60962  ORD-0060963            USB-C Hub          -0.49       1.0       4744.57
61386  ORD-0061387            USB-C Hub          -5.43       2.0       8393.02
61542  ORD-0061543  Wireless Headphones          -3.91       2.0      14344.32
61721  ORD-0061722           Power Bank          -0.11       2.0       5639.76
61942  ORD-0061943  Wireless Headphones          -1.02       2.0      17557.30
62346  ORD-0062347  Wireless Headphones          -3.11       3.0      24086.76
62544  ORD-0062545  Wireless Headphones          -0.73       2.0      14094.62
63058  ORD-0063059           Power Bank          -3.92       3.0      10529.65
63265  ORD-0063266  Wireless Headphones          -2.74       1.0       6683.20
63286  ORD-0063287           Power Bank          -1.09       1.0       3531.39
63620  ORD-0063621  Wireless Headphones          -0.20       2.0      15710.08
63648  ORD-0063649         Office Chair          -6.25       1.0      17672.91
63709  ORD-0063710            Air Fryer          -6.40       5.0      68940.77
63920  ORD-0063921           Power Bank          -3.11       3.0      10038.12
63951  ORD-0063952            USB-C Hub          -3.83       1.0       3891.01
64397  ORD-0064398            USB-C Hub          -3.98       1.0       3377.47
64475  ORD-0064476           Power Bank          -0.62       5.0      16522.11
64479  ORD-0064480            USB-C Hub          -9.00       4.0      13345.82
64774  ORD-0064775            USB-C Hub          -7.29       2.0       7257.31
64980  ORD-0064981    Bluetooth Speaker          -0.92       5.0      30786.72
65041  ORD-0065042            USB-C Hub          -3.08       1.0       4501.55
65418  ORD-0065419           Power Bank          -2.75       3.0       8575.27
65520  ORD-0065521            USB-C Hub          -8.78       2.0       8767.14
65536  ORD-0065537            USB-C Hub          -1.13       1.0       4025.24
65560  ORD-0065561    Bluetooth Speaker         -11.40       3.0      17089.79
65904  ORD-0065905    Bluetooth Speaker          -0.31       1.0       5291.05
66853  ORD-0066854           Power Bank          -6.28       3.0      11480.25
67718  ORD-0067719        Winter Jacket          -0.25       6.0      46058.98
68071  ORD-0068072  Wireless Headphones          -1.72       2.0      14290.24
68223  ORD-0068224  Wireless Headphones          -2.10       5.0      31259.42
68581  ORD-0068582           Power Bank          -2.73       1.0       4101.44
68989  ORD-0068990  Wireless Headphones          -8.87       2.0      13729.27
69524  ORD-0069525    Bluetooth Speaker          -0.74       2.0       9706.82
69630  ORD-0069631           Power Bank          -7.95       1.0       3559.19
70789  ORD-0070790            Air Fryer          -1.13       3.0      36150.52
70927  ORD-0070928            USB-C Hub          -3.39       3.0      11083.08
71109  ORD-0071110            USB-C Hub          -0.77       2.0       6820.38
71381  ORD-0071382            Air Fryer         -12.07       1.0      10135.00
71914  ORD-0071915            USB-C Hub          -6.27       2.0       8035.67
72015  ORD-0072016            USB-C Hub          -2.66       1.0       3760.53
72354  ORD-0072355    Bluetooth Speaker          -0.86       1.0       5478.77
72550  ORD-0072551                  NaN          -0.81       2.0       6888.49
73230  ORD-0073231    Bluetooth Speaker          -5.14       2.0      11114.42
73674  ORD-0073675           Power Bank          -0.11       1.0       3125.75
73681  ORD-0073682            USB-C Hub          -0.84       2.0       6078.13
74725  ORD-0074726    Bluetooth Speaker          -1.22       3.0      16033.60
75291  ORD-0075292            USB-C Hub          -6.06       2.0       6942.65
75688  ORD-0075689    Bluetooth Speaker          -6.51       2.0       9688.71
75804  ORD-0075805            USB-C Hub          -0.64       1.0       3893.80
75809  ORD-0075810    Bluetooth Speaker          -1.00       2.0      10393.82
75920  ORD-0075921         Office Chair          -1.82       3.0      59650.46
76081  ORD-0076082        Winter Jacket          -3.70       2.0      16642.70
76623  ORD-0076624    Bluetooth Speaker         -10.70       4.0      18677.26
76768  ORD-0076769            Air Fryer          -1.30       2.0      31145.07
76791  ORD-0076792           Power Bank          -4.03       1.0       3475.70
77469  ORD-0077470            USB-C Hub          -3.63       2.0       8153.28
77521  ORD-0077522            USB-C Hub          -0.39       3.0      13308.78
77529  ORD-0077530           Power Bank          -4.56       2.0       5483.08
77746  ORD-0077747            USB-C Hub          -1.54       2.0       8850.38
78361  ORD-0078362        Winter Jacket          -0.72       2.0      16357.05
78403  ORD-0078404           Power Bank          -1.20       3.0       9139.28
79517  ORD-0079518  Wireless Headphones          -1.16       1.0       6322.70
79558  ORD-0079559           Power Bank          -2.00       2.0       7807.82
79749  ORD-0079750           Power Bank          -0.78       4.0      13954.17
80514  ORD-0080515  Wireless Headphones          -2.26       2.0      15308.48
81112  ORD-0081113           Power Bank          -0.80       4.0      15144.68
81239  ORD-0081240            USB-C Hub          -0.95       3.0      10232.27
81255  ORD-0081256            USB-C Hub          -3.94       3.0      12738.12
81665  ORD-0081666           Power Bank          -1.75       1.0       3279.86

Data dengan diskon 100%

          Order_ID         Product_Name  Discount_Percent  Quantity  Sales_Amount
1706   ORD-0001707    Bluetooth Speaker             125.0       1.0       5671.31
26190  ORD-0026191           Face Serum             125.0       1.0       1940.67
27531  ORD-0027532  Wireless Headphones             125.0       2.0      15623.81
36584  ORD-0036585            Desk Lamp             125.0       2.0       3996.81
57212  ORD-0057213       Cotton T-Shirt             125.0       NaN       3011.53
57372  ORD-0057373        Running Shoes             125.0       1.0       5238.60
64964  ORD-0064965            Desk Lamp             125.0       5.0      11298.92
72298  ORD-0072299            Desk Lamp             125.0       2.0       6850.07

Data dengan gender tidak konsisten

          Order_ID         Product_Name      Gender  Quantity  Sales_Amount
43     ORD-0000044      Travel Backpack  Non-binary       2.0       6716.90
46     ORD-0000047       Cotton T-Shirt  Non-binary       2.0       3202.35
77     ORD-0000078            Desk Lamp  Non-binary       2.0       4961.21
403    ORD-0000404    Bluetooth Speaker  Non-binary       1.0       6222.84
521    ORD-0000522              Perfume  Non-binary       1.0       6426.57
609    ORD-0000610      Ceramic Mug Set  Non-binary       4.0       5899.71
616    ORD-0000617          Denim Jeans  Non-binary       1.0       3181.44
810    ORD-0000811          Denim Jeans  Non-binary       4.0      10483.02
876    ORD-0000877         Bedsheet Set  Non-binary       1.0       4141.62
986    ORD-0000987        Winter Jacket  Non-binary       4.0      33680.79
1018   ORD-0001019        Notebook Pack  Non-binary       3.0       2363.57
1130   ORD-0001131         Laptop Stand  Non-binary       1.0       3212.75
1131   ORD-0001132        Running Shoes  Non-binary       2.0      10395.03
1204   ORD-0001205            Air Fryer  Non-binary       1.0      20039.29
1375   ORD-0001376                  NaN  Non-binary       2.0       4050.59
1394   ORD-0001395  Wireless Headphones  Non-binary       4.0      33448.92
1430   ORD-0001431        Skin Care Kit  Non-binary       2.0       7844.07
1547   ORD-0001548  Wireless Headphones  Non-binary       2.0      15756.77
1793   ORD-0001794       Cotton T-Shirt  Non-binary       2.0       2952.05
2067   ORD-0002068        Notebook Pack  Non-binary       4.0       2756.93
2071   ORD-0002072            USB-C Hub  Non-binary       3.0      13699.37
2079   ORD-0002080           Board Game  Non-binary       1.0       2488.00
2111   ORD-0002112        Skin Care Kit  Non-binary       3.0      13159.81
2303   ORD-0002304          Denim Jeans  Non-binary       3.0       7802.29
2363   ORD-0002364           Board Game  Non-binary       2.0       5195.25
2404   ORD-0002405        Running Shoes  Non-binary       3.0      15590.98
2453   ORD-0002454           Face Serum  Non-binary       1.0       1847.20
2614   ORD-0002615          Denim Jeans  Non-binary       2.0       7376.59
2818   ORD-0002819        Skin Care Kit  Non-binary       5.0      19857.62
3360   ORD-0003361         Office Chair  Non-binary       2.0      40552.21
3502   ORD-0003503       Cotton T-Shirt  Non-binary       4.0       5606.80
3581   ORD-0003582        Notebook Pack  Non-binary       3.0       2246.08
3681   ORD-0003682       Cotton T-Shirt  Non-binary       2.0       3058.08
3719   ORD-0003720            Air Fryer  Non-binary       1.0      17857.94
3921   ORD-0003922         Bedsheet Set  Non-binary       2.0       8165.23
3972   ORD-0003973            USB-C Hub  Non-binary       2.0       8680.32
3989   ORD-0003990       Cotton T-Shirt  Non-binary       1.0       1888.19
4047   ORD-0004048            Air Fryer  Non-binary       2.0      30039.91
4051   ORD-0004052         Office Chair  Non-binary       4.0      78667.91
4058   ORD-0004059            Air Fryer  Non-binary       2.0      31249.33
4160   ORD-0004161    Smart Watch Strap  Non-binary       1.0       1360.85
4188   ORD-0004189      Ceramic Mug Set  Non-binary       1.0       1781.16
4265   ORD-0004266    Smart Watch Strap  Non-binary       1.0       1430.44
4291   ORD-0004292        Running Shoes  Non-binary       3.0      17396.05
4320   ORD-0004321            USB-C Hub  Non-binary       2.0       7865.15
4466   ORD-0004467  Wireless Headphones  Non-binary       1.0       7990.25
4490   ORD-0004491         Laptop Stand  Non-binary       2.0       7410.81
4495   ORD-0004496  Wireless Headphones  Non-binary       2.0      15986.36
4510   ORD-0004511          Denim Jeans  Non-binary       NaN       3084.97
4530   ORD-0004531        Running Shoes  Non-binary       1.0       4845.38
4549   ORD-0004550           Board Game  Non-binary       1.0       2820.02
4664   ORD-0004665    Bluetooth Speaker  Non-binary       1.0       5357.91
4739   ORD-0004740              Perfume  Non-binary       5.0      28329.83
4811   ORD-0004812        Notebook Pack  Non-binary       5.0       3442.30
4848   ORD-0004849           Power Bank  Non-binary       3.0       9588.26
4899   ORD-0004900    Bluetooth Speaker  Non-binary       4.0      23886.78
4986   ORD-0004987        Notebook Pack  Non-binary       3.0       2058.02
5078   ORD-0005079        Notebook Pack  Non-binary       3.0       1983.83
5121   ORD-0005122        Skin Care Kit  Non-binary       4.0      16902.74
5155   ORD-0005156      Ceramic Mug Set  Non-binary       1.0       2003.60
5163   ORD-0005164            Air Fryer  Non-binary       4.0      68030.69
5167   ORD-0005168            Desk Lamp  Non-binary       2.0       5291.31
5219   ORD-0005220              Perfume  Non-binary       1.0       6248.23
5227   ORD-0005228        Skin Care Kit  Non-binary       1.0       4357.11
5232   ORD-0005233          Denim Jeans  Non-binary       3.0       9459.32
5352   ORD-0005353       Cotton T-Shirt  Non-binary       3.0       4711.85
5467   ORD-0005468       Cotton T-Shirt  Non-binary       2.0       2812.06
5489   ORD-0005490           Board Game  Non-binary       2.0       4791.68
5576   ORD-0005577            Desk Lamp  Non-binary       2.0       4461.24
5594   ORD-0005595            Air Fryer  Non-binary       1.0      16634.24
5634   ORD-0005635          Denim Jeans  Non-binary       NaN       7890.95
5764   ORD-0005765        Notebook Pack  Non-binary       2.0       1497.94
6011   ORD-0006012            Desk Lamp  Non-binary       NaN       2330.97
6058   ORD-0006059    Bluetooth Speaker  Non-binary       1.0       5528.37
6222   ORD-0006223       Cotton T-Shirt  Non-binary       2.0       3089.07
6259   ORD-0006260       Cotton T-Shirt  Non-binary       5.0       7516.31
6356   ORD-0006357    Bluetooth Speaker  Non-binary       2.0       9717.00
6570   ORD-0006571      Ceramic Mug Set  Non-binary       2.0       4255.33
6679   ORD-0006680           Power Bank  Non-binary       2.0       7177.44
6827   ORD-0006828           Face Serum  Non-binary       1.0       2286.02
6941   ORD-0006942    Bluetooth Speaker  Non-binary       1.0       4820.69
7069   ORD-0007070        Skin Care Kit  Non-binary       2.0       8019.15
7102   ORD-0007103  Wireless Headphones  Non-binary       3.0      25448.69
7242   ORD-0007243    Smart Watch Strap  Non-binary       4.0       4902.98
7306   ORD-0007307      Ceramic Mug Set  Non-binary       4.0       6630.52
7309   ORD-0007310    Bluetooth Speaker  Non-binary       1.0       5196.74
7352   ORD-0007353       Cotton T-Shirt  Non-binary       3.0       3925.24
7370   ORD-0007371    Smart Watch Strap  Non-binary       2.0       2785.75
7452   ORD-0007453      Travel Backpack  Non-binary       2.0       7611.54
7455   ORD-0007456      Ceramic Mug Set  Non-binary       2.0       4008.00
7492   ORD-0007493      Ceramic Mug Set  Non-binary       1.0       1572.45
7645   ORD-0007646           Power Bank  Non-binary       2.0       7994.74
7737   ORD-0007738           Power Bank  Non-binary       3.0      10914.76
7753   ORD-0007754                  NaN  Non-binary       1.0       3143.45
7783   ORD-0007784  Wireless Headphones  Non-binary       2.0      16340.74
7840   ORD-0007841              Perfume  Non-binary       3.0      18244.90
7903   ORD-0007904         Bedsheet Set  Non-binary       6.0      26217.64
7932   ORD-0007933    Bluetooth Speaker  Non-binary       1.0       5354.29
7945   ORD-0007946            Desk Lamp  Non-binary       4.0      10279.34
8010   ORD-0008011        Winter Jacket  Non-binary       3.0      29201.17
8022   ORD-0008023         Bedsheet Set  Non-binary       1.0       3975.00
8090   ORD-0008091        Running Shoes  Non-binary       8.0      44075.42
8137   ORD-0008138              Perfume  Non-binary       3.0      19490.13
8168   ORD-0008169    Smart Watch Strap  Non-binary       3.0       3574.28
8169   ORD-0008170                  NaN  Non-binary       2.0       7663.08
8288   ORD-0008289              Perfume  Non-binary       3.0      20439.85
8393   ORD-0008394         Laptop Stand  Non-binary       1.0       3727.47
8464   ORD-0008465      Building Blocks  Non-binary       2.0       5831.67
8479   ORD-0008480      Ceramic Mug Set  Non-binary       1.0       2001.06
8663   ORD-0008664              Perfume  Non-binary       6.0      38024.87
8705   ORD-0008706  Wireless Headphones  Non-binary       3.0      23878.53
8794   ORD-0008795          Denim Jeans  Non-binary       1.0       3236.29
8988   ORD-0008989    Bluetooth Speaker  Non-binary       3.0      14994.69
9055   ORD-0009056        Winter Jacket  Non-binary       5.0      45925.84
9061   ORD-0009062    Smart Watch Strap  Non-binary       3.0       4087.09
9076   ORD-0009077      Ceramic Mug Set  Non-binary       1.0       1826.94
9136   ORD-0009137        Skin Care Kit  Non-binary       1.0       5225.32
9256   ORD-0009257           Board Game  Non-binary       2.0       4860.37
9285   ORD-0009286           Power Bank  Non-binary       3.0       9498.80
9309   ORD-0009310           Face Serum  Non-binary       3.0       5581.19
9389   ORD-0009390            USB-C Hub  Non-binary       2.0       8618.62
9408   ORD-0009409          Denim Jeans  Non-binary       2.0       6468.71
9414   ORD-0009415         Laptop Stand  Non-binary       1.0       3620.06
9419   ORD-0009420           Power Bank  Non-binary       2.0       6493.87
9427   ORD-0009428      Building Blocks  Non-binary       3.0       8016.30
9622   ORD-0009623                  NaN  Non-binary       3.0       5981.09
9642   ORD-0009643       Cotton T-Shirt  Non-binary       1.0       1532.08
9886   ORD-0009887           Face Serum  Non-binary       1.0       2410.59
9891   ORD-0009892           Board Game  Non-binary       2.0       4866.48
9913   ORD-0009914         Bedsheet Set  Non-binary       2.0       8608.92
9928   ORD-0009929        Skin Care Kit  Non-binary       1.0       4395.85
9996   ORD-0009997       Cotton T-Shirt  Non-binary       2.0       3410.59
10026  ORD-0010027           Face Serum  Non-binary       2.0       2935.05
10159  ORD-0010160            USB-C Hub  Non-binary       4.0      19690.37
10228  ORD-0010229  Wireless Headphones  Non-binary       3.0      24267.72
10475  ORD-0010476          Denim Jeans  Non-binary       2.0       5490.86
10633  ORD-0010634           Power Bank  Non-binary       1.0       3708.66
10730  ORD-0010731                  NaN  Non-binary       2.0       6582.17
10770  ORD-0010771           Face Serum  Non-binary       2.0       3532.37
10822  ORD-0010823            USB-C Hub  Non-binary       2.0       7406.31
10838  ORD-0010839        Running Shoes  Non-binary       1.0       4690.04
10880  ORD-0010881           Board Game  Non-binary       3.0       7482.64
10881  ORD-0010882        Running Shoes  Non-binary       1.0       5703.86
10882  ORD-0010883         Laptop Stand  Non-binary       2.0       6619.00
11023  ORD-0011024  Wireless Headphones  Non-binary       1.0       6843.56
11171  ORD-0011172      Ceramic Mug Set  Non-binary       2.0       3538.17
11198  ORD-0011199          Denim Jeans  Non-binary       3.0       9636.13
11207  ORD-0011208    Bluetooth Speaker  Non-binary       2.0      10060.80
11476  ORD-0011477         Bedsheet Set  Non-binary       4.0      17396.65
11534  ORD-0011535      Building Blocks  Non-binary       4.0       8917.15
11539  ORD-0011540                  NaN  Non-binary       3.0      15239.90
11589  ORD-0011590  Wireless Headphones  Non-binary       2.0      14697.17
11687  ORD-0011688  Wireless Headphones  Non-binary       4.0      27374.36
11741  ORD-0011742           Board Game  Non-binary       5.0      13141.03
11853  ORD-0011854       Cotton T-Shirt  Non-binary       1.0       1463.71
11976  ORD-0011977        Skin Care Kit  Non-binary       3.0      14984.85
12041  ORD-0012042       Cotton T-Shirt  Non-binary       3.0       3506.83
12047  ORD-0012048        Running Shoes  Non-binary       2.0      11569.40
12049  ORD-0012050    Bluetooth Speaker  Non-binary       2.0      12300.09
12141  ORD-0012142    Smart Watch Strap  Non-binary       2.0       2882.49
12147  ORD-0012148           Face Serum  Non-binary       1.0       2066.17
12293  ORD-0012294        Notebook Pack  Non-binary       2.0       1566.62
12400  ORD-0012401      Ceramic Mug Set  Non-binary       1.0       2122.67
12575  ORD-0012576        Running Shoes  Non-binary       1.0       6065.24
12597  ORD-0012598      Ceramic Mug Set  Non-binary       3.0       4384.17
12602  ORD-0012603           Face Serum  Non-binary       3.0       7042.09
12639  ORD-0012640         Office Chair  Non-binary       1.0      20537.54
12700  ORD-0012701         Bedsheet Set  Non-binary       4.0      17964.04
12784  ORD-0012785      Ceramic Mug Set  Non-binary       1.0       2145.83
12790  ORD-0012791      Building Blocks  Non-binary       2.0       5918.48
12837  ORD-0012838        Notebook Pack  Non-binary       4.0       2634.35
12866  ORD-0012867        Skin Care Kit  Non-binary       2.0       9897.87
12869  ORD-0012870       Cotton T-Shirt  Non-binary       2.0       3297.05
12926  ORD-0012927  Wireless Headphones  Non-binary       1.0       8101.78
12962  ORD-0012963              Perfume  Non-binary       1.0       6849.68
13038  ORD-0013039        Skin Care Kit  Non-binary       2.0       7340.50
13108  ORD-0013109         Office Chair  Non-binary       1.0      25682.01
13262  ORD-0013263          Denim Jeans  Non-binary       2.0       6678.05
13303  ORD-0013304         Office Chair  Non-binary       3.0      60690.10
13387  ORD-0013388    Smart Watch Strap  Non-binary       4.0       5614.91
13431  ORD-0013432       Cotton T-Shirt  Non-binary       4.0       6627.96
13433  ORD-0013434            Desk Lamp  Non-binary       5.0      13928.82
13434  ORD-0013435    Bluetooth Speaker  Non-binary       3.0      17985.29
13437  ORD-0013438           Power Bank  Non-binary       1.0       3758.81
13465  ORD-0013466  Wireless Headphones  Non-binary       3.0      27065.09
13559  ORD-0013560      Ceramic Mug Set  Non-binary       3.0       5490.12
13583  ORD-0013584            Desk Lamp  Non-binary       3.0       7881.42
13602  ORD-0013603       Cotton T-Shirt  Non-binary       3.0       4193.10
13639  ORD-0013640    Bluetooth Speaker  Non-binary       2.0      11594.35
13785  ORD-0013786            USB-C Hub  Non-binary       2.0       8608.19
13788  ORD-0013789        Notebook Pack  Non-binary       3.0       1768.05
13790  ORD-0013791         Laptop Stand  Non-binary       2.0       5344.32
13859  ORD-0013860       Cotton T-Shirt  Non-binary       1.0       1568.07
13872  ORD-0013873    Smart Watch Strap  Non-binary       3.0       4315.50
13877  ORD-0013878       Cotton T-Shirt  Non-binary       3.0       4192.75
13973  ORD-0013974       Cotton T-Shirt  Non-binary       1.0       1722.79
13997  ORD-0013998        Running Shoes  Non-binary       1.0       5691.54
14006  ORD-0014007       Cotton T-Shirt  Non-binary       2.0       2927.66
14161  ORD-0014162       Cotton T-Shirt  Non-binary       1.0       1955.91
14190  ORD-0014191          Denim Jeans  Non-binary       4.0      13592.13
14314  ORD-0014315           Face Serum  Non-binary       2.0       4364.41
14357  ORD-0014358    Bluetooth Speaker  Non-binary       1.0       5966.55
14364  ORD-0014365  Wireless Headphones  Non-binary       2.0      12847.00
14419  ORD-0014420         Bedsheet Set  Non-binary       1.0       3788.93
14537  ORD-0014538    Bluetooth Speaker  Non-binary       2.0      11690.60
14541  ORD-0014542      Building Blocks  Non-binary       3.0       8466.99
14593  ORD-0014594         Bedsheet Set  Non-binary       3.0      10097.01
14626  ORD-0014627           Power Bank  Non-binary       2.0       7955.62
14628  ORD-0014629  Wireless Headphones  Non-binary       3.0      20898.00
14751  ORD-0014752              Perfume  Non-binary       2.0      10487.37
14812  ORD-0014813              Perfume  Non-binary       1.0       6395.54
14863  ORD-0014864        Notebook Pack  Non-binary       2.0       1395.34
14896  ORD-0014897         Laptop Stand  Non-binary       3.0       9530.11
15048  ORD-0015049    Smart Watch Strap  Non-binary       3.0       4498.24
15337  ORD-0015338         Laptop Stand  Non-binary       1.0       3339.85
15373  ORD-0015374         Laptop Stand  Non-binary       3.0       8689.29
15452  ORD-0015453            USB-C Hub  Non-binary       3.0      15345.07
15469  ORD-0015470      Travel Backpack  Non-binary       3.0       9892.60
15486  ORD-0015487  Wireless Headphones  Non-binary       1.0       7185.07
15729  ORD-0015730            USB-C Hub  Non-binary       2.0       9058.51
15745  ORD-0015746      Travel Backpack  Non-binary       3.0      11995.49
15756  ORD-0015757      Ceramic Mug Set  Non-binary       2.0       3752.93
15765  ORD-0015766           Face Serum  Non-binary       1.0       2585.57
15934  ORD-0015935      Ceramic Mug Set  Non-binary       3.0       5278.71
15966  ORD-0015967      Travel Backpack  Non-binary       3.0      10496.77
15970  ORD-0015971        Winter Jacket  Non-binary       1.0       9236.47
15993  ORD-0015994           Board Game  Non-binary       2.0       5566.70
15998  ORD-0015999        Notebook Pack  Non-binary       2.0       1471.77
16084  ORD-0016085    Smart Watch Strap  Non-binary       1.0       1583.13
16133  ORD-0016134      Building Blocks  Non-binary       4.0      12215.66
16321  ORD-0016322       Cotton T-Shirt  Non-binary       2.0       2830.82
16325  ORD-0016326            Desk Lamp  Non-binary       1.0       2684.13
16538  ORD-0016539           Board Game  Non-binary       3.0       7386.43
16548  ORD-0016549      Ceramic Mug Set  Non-binary       4.0       6193.33
16647  ORD-0016648        Notebook Pack  Non-binary       1.0        711.31
16734  ORD-0016735         Laptop Stand  Non-binary       1.0       3075.39
16779  ORD-0016780        Winter Jacket  Non-binary       4.0      28499.64
16785  ORD-0016786  Wireless Headphones  Non-binary       1.0       8279.70
16983  ORD-0016984  Wireless Headphones  Non-binary       NaN      16242.33
17003  ORD-0017004              Perfume  Non-binary       2.0      13782.76
17045  ORD-0017046  Wireless Headphones  Non-binary       3.0      25689.61
17057  ORD-0017058       Cotton T-Shirt  Non-binary       3.0       4112.26
17101  ORD-0017102    Smart Watch Strap  Non-binary       2.0       2216.19
17110  ORD-0017111           Face Serum  Non-binary       3.0       5108.77
17135  ORD-0017136         Bedsheet Set  Non-binary       6.0      18643.07
17297  ORD-0017298    Bluetooth Speaker  Non-binary       1.0       5165.85
17414  ORD-0017415          Denim Jeans  Non-binary       2.0       6977.48
17656  ORD-0017657        Skin Care Kit  Non-binary       1.0       4757.35
17826  ORD-0017827      Travel Backpack  Non-binary       1.0       3166.48
17845  ORD-0017846        Notebook Pack  Non-binary       2.0       1368.06
17847  ORD-0017848      Ceramic Mug Set  Non-binary       2.0       2981.37
17891  ORD-0017892        Winter Jacket  Non-binary       8.0      50761.48
18013  ORD-0018014      Travel Backpack  Non-binary       2.0       6824.13
18034  ORD-0018035                  NaN  Non-binary       2.0       3574.20
18283  ORD-0018284      Travel Backpack  Non-binary       1.0       3849.61
18413  ORD-0018414              Perfume  Non-binary       1.0       6803.85
18579  ORD-0018580           Power Bank  Non-binary       3.0      11685.61
18587  ORD-0018588            USB-C Hub  Non-binary       3.0      13429.38
18606  ORD-0018607         Bedsheet Set  Non-binary       1.0       4048.04
18646  ORD-0018647    Smart Watch Strap  Non-binary       2.0       2372.67
18655  ORD-0018656      Ceramic Mug Set  Non-binary       2.0       3459.66
18682  ORD-0018683    Smart Watch Strap  Non-binary       3.0       5080.03

---

# Menampilkan data yang tidak konsisten
`Uji` `pada` `kolom` `gender`

In [6]:
csv.head(0)

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Age, Gender, City, Region, Customer_Segment, Sales_Channel, Product_ID, Product_Category, Product_Name, Unit_Price, Quantity, Discount_Percent, Shipping_Cost, Payment_Method, Order_Status, Return_Flag, Marketing_Channel, Customer_Rating, Sales_Amount, Profit_Margin]
Index: []

In [7]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.width',100)
cat_col=['Gender','City','Region','Sales_Channel','Payment_Method', 'Customer_Segment', 'Product_Category', 'Order_Status', 'Return_Flag', 'Marketing_Channel']

for col in cat_col:
    print(f'\n=== {col} ({csv[col].nunique()} variasi unik) ===')
    print(csv[col].value_counts(dropna=False))
    print()

=== Gender (10 variasi unik) ===
Gender
Male                 40286
Female               39375
NaN                   3161
Prefer not to say     2983
Non-binary            1318
 FEMALE                517
male                   488
 MALE                  487
F                      473
M                      452
female                 444
Name: count, dtype: int64


=== City (18 variasi unik) ===
City
Karachi         18397
Lahore          15365
Rawalpindi       8524
Islamabad        7944
Faisalabad       6884
Peshawar         6212
Multan           5399
Gujranwala       4302
Hyderabad        3963
Sialkot          3507
Quetta           3029
Abbottabad       2714
NaN              2205
 KARACHI          365
karachi           348
 LAHORE           271
lahore            249
 Rawalpindi       157
rawalpindi        149
Name: count, dtype: int64


=== Region (5 variasi unik) ===
Region
Punjab                         45957
Sindh                          23641
Khyber Pakhtunkhwa              9161
Islamabad Capital Territory     8130
Balochistan                     3095
Name: count, dtype: int64


=== Sales_Channel (10 variasi unik) ===
Sales_Channel
Online            39279
Marketplace       21168
Retail Store      20455
Phone Order        5289
NaN                1675
 ONLINE             502
E-commerce          476
online              470
retail store        242
Retail              232
 RETAIL STORE       196
Name: count, dtype: int64


=== Payment_Method (11 variasi unik) ===
Payment_Method
Cash on Delivery      27653
Digital Wallet        18871
Debit Card            16633
Credit Card           12490
Bank Transfer          6703
NaN                    5959
COD                     347
cash on delivery        333
 CASH ON DELIVERY       327
Wallet                  235
 DIGITAL WALLET         223
digital wallet          210
Name: count, dtype: int64


=== Customer_Segment (8 variasi unik) ===
Customer_Segment
Returning      36637
New            21434
Loyal          19740
Corporate       5936
NaN             4121
returning        712
 RETURNING       648
loyal            395
 LOYAL           361
Name: count, dtype: int64


=== Product_Category (8 variasi unik) ===
Product_Category
Electronics        19754
Clothing           16356
Home & Kitchen     14685
Beauty             11641
Accessories         8140
Toys & Games        6813
Office Supplies     6060
Stationery          5456
NaN                 1079
Name: count, dtype: int64


=== Order_Status (7 variasi unik) ===
Order_Status
Delivered           64801
Shipped              9203
Processing           5806
Cancelled            3293
Returned             2965
NaN                  2020
Refunded             1390
Return Requested      506
Name: count, dtype: int64


=== Return_Flag (2 variasi unik) ===
Return_Flag
No     85019
Yes     4965
Name: count, dtype: int64


=== Marketing_Channel (12 variasi unik) ===
Marketing_Channel
Search            18877
Social Media      17377
Direct            13228
Email              9831
Influencer         8306
Affiliate          7624
NaN                7619
SMS                5778
search              371
 SEARCH             357
social media        215
 SOCIAL MEDIA       208
Social              193
Name: count, dtype: int64

standarisasi nilai yang tidak konsisten

In [8]:
csv['Gender']=csv['Gender'].str.lower().str.strip()
Gender_map={
    'male': 'Male',
    'm': 'Male',
    'female': 'Female',
    'f': 'Female',
    'non-binary': 'Non-binary',
    'nan': 'N/A',
    'prefer not to say': 'Prefer not to say'
}
csv['Gender']=csv['Gender'].map(Gender_map)
print(csv['Gender'].value_counts(dropna=False))

Gender
Male                 41713
Female               40809
NaN                   3161
Prefer not to say     2983
Non-binary            1318
Name: count, dtype: int64

In [9]:
print(csv['Gender'].unique().tolist())

['Female', 'Male', nan, 'Prefer not to say', 'Non-binary']

In [10]:
csv['City'] = csv['City'].str.lower().str.strip()

city_map = {
    'karachi': 'Karachi',
    'lahore': 'Lahore',
    'rawalpindi': 'Rawalpindi',
    'islamabad': 'Islamabad',
    'faisalabad': 'Faisalabad',
    'peshawar': 'Peshawar',
    'multan': 'Multan',
    'gujranwala': 'Gujranwala',
    'hyderabad': 'Hyderabad',
    'sialkot': 'Sialkot',
    'quetta': 'Quetta'
}

csv['City'] = csv['City'].map(city_map)

print(csv['City'].value_counts(dropna=False))

City
Karachi       19110
Lahore        15885
Rawalpindi     8830
Islamabad      7944
Faisalabad     6884
Peshawar       6212
Multan         5399
NaN            4919
Gujranwala     4302
Hyderabad      3963
Sialkot        3507
Quetta         3029
Name: count, dtype: int64

In [11]:
csv['Sales_Channel']=csv['Sales_Channel'].str.lower().str.strip()

Sales_Channel_map={
    'online': 'Online',
    'e-commerce': 'Online',       # E-commerce = Online
    'marketplace': 'Marketplace',
    'retail store': 'Retail Store',
    'retail': 'Retail Store',      # Retail = Retail Store
    'phone order': 'Phone Order'
}
csv['Sales_Channel']=csv['Sales_Channel'].map(Sales_Channel_map)
print(csv['Sales_Channel'].value_counts(dropna=False))

Sales_Channel
Online          40727
Marketplace     21168
Retail Store    21125
Phone Order      5289
NaN              1675
Name: count, dtype: int64

In [16]:
csv['Payment_Method']=csv['Payment_Method'].str.lower().str.strip()

Payment_Method_map={
'COD':'Cash On Delivery',
'cash on delivery' : 'Cash On Delivery',
'CASH ON DELIVERY':'Cash On Delivery',
'Wallet':'Digital Wallet',
 'DIGITAL WALLET' : 'Digital Wallet',
'digital wallet': 'Digital Wallet',
'debit card': 'Debit Card',
'credit card': 'Credit Card',
'bank tf':'Bank Transfer'
}

csv['Payment_Method']=csv['Payment_Method'].map(Payment_Method_map)
print(csv['Payment_Method'].value_counts(dropna=False))

Payment_Method
NaN                 42367
Cash On Delivery    28313
Digital Wallet      19304
Name: count, dtype: int64