```
Pemanggilan data

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.width',1000)

path=r"C:\Users\sayyi\Downloads\sales_dataset_89984_records_23_features.csv"
missing_format=['None', 'none', 'null', '?', ' ', '   ', 'n/a', 'na', '--', '-']
csv=pd.read_csv(path, na_values=missing_format)

print(csv.shape)
print(csv.dtypes)
csv.head(4)

(89984, 23)
Order_ID                 str
Order_Date               str
Customer_ID              str
Customer_Age         float64
Gender                   str
City                     str
Region                   str
Customer_Segment         str
Sales_Channel            str
Product_ID               str
Product_Category         str
Product_Name             str
Unit_Price           float64
Quantity             float64
Discount_Percent     float64
Shipping_Cost        float64
Payment_Method           str
Order_Status             str
Return_Flag              str
Marketing_Channel        str
Customer_Rating      float64
Sales_Amount         float64
Profit_Margin        float64
dtype: object

      Order_ID  Order_Date Customer_ID  Customer_Age  Gender        City  Region Customer_Segment Sales_Channel Product_ID Product_Category  Product_Name  Unit_Price  Quantity  Discount_Percent  Shipping_Cost    Payment_Method Order_Status Return_Flag Marketing_Channel  Customer_Rating  Sales_Amount  Profit_Margin
0  ORD-0000001  2024-01-09  CUS-020443          64.0  Female     Karachi   Sindh        Corporate  Retail Store    PRD-018  Office Supplies  Laptop Stand     3746.16       2.0              8.33         119.36       Credit Card    Delivered          No            Direct              5.0       6987.71          27.20
1  ORD-0000002  2025-06-13  CUS-025451          40.0    Male  Rawalpindi  Punjab              New   Marketplace    PRD-011   Home & Kitchen  Bedsheet Set     4203.05       1.0              9.38         167.96  Cash on Delivery    Delivered          No      Social Media              5.0       3976.91          31.46
2  ORD-0000003  2025-09-25  CUS-022569          56.0    Male      Lahore  Punjab        Returning   Marketplace    PRD-021     Toys & Games    Board Game     2723.85       5.0             17.63         250.01        Debit Card    Delivered          No            Search              3.0      11467.71          30.81
3  ORD-0000004  2024-01-01  CUS-010322          31.0    male  Rawalpindi  Punjab            Loyal   Marketplace    PRD-017  Office Supplies  Office Chair    24977.53       3.0              8.10            NaN  Cash on Delivery    Delivered          No            Direct              5.0      69182.12          25.20

In [7]:
null_count=csv.isnull().sum()
null_percent=(csv.isnull().mean()*100).round(2)
summary=pd.DataFrame({
    'Null Count':null_count,
    'Null Percent':null_percent
}).sort_values('Null Count',ascending=False)
summary

                   Null Count  Null Percent
Customer_Rating         22558         25.07
Marketing_Channel        7619          8.47
Shipping_Cost            6779          7.53
Payment_Method           5959          6.62
Customer_Age             4966          5.52
Customer_Segment         4121          4.58
Discount_Percent         4058          4.51
Profit_Margin            3224          3.58
Gender                   3161          3.51
Unit_Price               2516          2.80
City                     2205          2.45
Order_Status             2020          2.24
Sales_Channel            1675          1.86
Product_Name             1672          1.86
Product_Category         1079          1.20
Quantity                  998          1.11
Order_ID                    0          0.00
Order_Date                  0          0.00
Customer_ID                 0          0.00
Region                      0          0.00
Product_ID                  0          0.00
Return_Flag                 0          0.00
Sales_Amount                0          0.00